mysql:
  dsn: "root:password@tcp(localhost:3306)/zhihu?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 10
  max_idle_conns: 5

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

admin:
  username: "your_admin_username"
  password: "your_admin_password"